version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: echo-service-es
    environment:
      - cluster.name=echo_service
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "transport.host=127.0.0.1"
      - "http.host: 0.0.0.0"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - echo-service:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - echo-service

volumes:
  echo-service:
    driver: local

networks:
  echo-service:
    driver: bridge